/* VELMORA admin dashboard. Prototype PIN is client-side and not production security. */
const ADMIN_TABS=["overview","products","orders","branding","design","homepage","payment","shipping","seo","social","backup","settings"];
let adminTab="overview",editingProductId=null,adminUnlocked=false;

function adminOpen(){if(adminUnlocked){$("#adminShell").classList.remove("hidden");$("#adminLogin").classList.add("hidden");$("#adminApp").classList.remove("hidden");renderAdmin()}else{$("#adminShell").classList.remove("hidden");$("#adminLogin").classList.remove("hidden");$("#adminApp").classList.add("hidden");$("#adminPin").value="";$("#loginError").textContent=""}}
function adminClose(){$("#adminShell").classList.add("hidden");document.body.classList.remove("no-scroll")}
$("#adminTrigger").onclick=adminOpen;$("#closeAdminLogin").onclick=adminClose;$("#loginBtn").onclick=()=>{if($("#adminPin").value===STORE.admin.pin){adminUnlocked=true;$("#adminLogin").classList.add("hidden");$("#adminApp").classList.remove("hidden");renderAdmin()}else $("#loginError").textContent="Invalid PIN."};$("#adminPin").onkeydown=e=>{if(e.key==="Enter")$("#loginBtn").click()};$("#exitAdmin").onclick=()=>{adminUnlocked=false;adminClose()};
$$(".admin-tab").forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;renderAdmin()});$("#previewStore").onclick=()=>adminClose();

function toast(msg="Saved successfully"){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove("show"),1800)}
function renderAdmin(){if(!adminUnlocked)return;$("#adminTitle").textContent=adminTab[0].toUpperCase()+adminTab.slice(1);$$(".admin-tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===adminTab));const views={overview:overviewView,products:productsView,orders:ordersView,branding:brandingView,design:designView,homepage:homepageView,payment:paymentView,shipping:shippingView,seo:seoView,social:socialView,backup:backupView,settings:settingsView};$("#adminContent").innerHTML=views[adminTab]();bindAdminView()}
function saveAndRender(msg){saveStore(STORE);renderStore();renderAdmin();toast(msg||"Saved successfully")}
function field(label,name,value="",type="text",wide=false,extra=""){return `<div class="admin-field ${wide?"wide":""}"><label>${label}</label>${type==="textarea"?`<textarea name="${name}" ${extra}>${escapeHtml(value)}</textarea>`:`<input name="${name}" type="${type}" value="${escapeHtml(value)}" ${extra}>`}</div>`}
function selectField(label,name,value,options,wide=false){return `<div class="admin-field ${wide?"wide":""}"><label>${label}</label><select name="${name}">${options.map(o=>`<option value="${escapeHtml(o[0])}" ${o[0]===value?"selected":""}>${escapeHtml(o[1])}</option>`).join("")}</select></div>`}
function boolField(label,name,val){return `<label class="check"><input type="checkbox" name="${name}" ${val?"checked":""}> ${label}</label>`}
function overviewView(){const revenue=STORE.orders.filter(o=>o.paymentStatus==="Paid").reduce((s,o)=>s+o.total,0);const margin=STORE.products.filter(p=>p.published).reduce((s,p)=>s+(p.price-p.supplierCost-p.shippingCost-p.price*(STORE.profit.paymentFeePercent/100)-STORE.profit.paymentFixed),0);return `<div class="stats"><div class="stat"><span>TOTAL PRODUCTS</span><strong>${STORE.products.length}</strong></div><div class="stat"><span>PUBLISHED</span><strong>${STORE.products.filter(p=>p.published).length}</strong></div><div class="stat"><span>ORDERS</span><strong>${STORE.orders.length}</strong></div><div class="stat"><span>REVENUE (PAID)</span><strong>${money(revenue)}</strong></div><div class="stat"><span>EST. GROSS MARGIN</span><strong>${money(margin)}</strong></div></div><div class="admin-grid" style="margin-top:15px"><div class="admin-card"><h3>Store status</h3><p class="preview-note">Prototype mode: localStorage stores settings/products in this browser only. It is not a secure production database.</p></div><div class="admin-card"><h3>Quick actions</h3><div class="admin-actions"><button class="admin-btn dark" data-goto="products">Manage products</button><button class="admin-btn" data-goto="design">Change theme</button><button class="admin-btn" data-goto="backup">Export backup</button></div></div></div>`}
function productsView(){const p=STORE.products.find(x=>x.id===editingProductId);return `<div class="admin-card"><h3>${p?"Edit product":"Add product"}</h3><form id="productForm" class="form-grid">${field("Product name","name",p?.name||"")}${field("Product ID / SKU","id",p?.id||"VM-"+String(Date.now()).slice(-6))}${field("Main image URL","mainImage",p?.images?.[0]||"", "text",true)}${field("Additional image URLs (one per line)","additionalImages",p?.images?.slice(1).join("\\n")||"","textarea",true)}${field("Short description","short",p?.short||"")}${field("Full description","description",p?.description||"","textarea",true)}${field("Selling price","price",p?.price??"","number")}${field("Compare-at/original price","compare",p?.compare??"","number")}${selectField("Currency","currency",p?.currency||STORE.payment.currency,[["USD","USD"],["GBP","GBP"],["EUR","EUR"],["AUD","AUD"]])}${field("Category","category",p?.category||"")}${field("Product tags","tags",p?.tags?.join(", ")||"")}${field("Variants JSON","variants",JSON.stringify(p?.variants||[]),"text",true,"placeholder='[{\"name\":\"Colour\",\"options\":[\"Stone\",\"Black\"]}]'")}${field("Shipping information","shipping",p?.shipping||"")}${field("Supplier name","supplier",p?.supplier||"")}${field("Supplier product URL","supplierUrl",p?.supplierUrl||"","url")}${field("Supplier product ID","supplierProductId",p?.supplierProductId||"")}${field("Supplier cost","supplierCost",p?.supplierCost??0,"number")}${field("Shipping cost","shippingCost",p?.shippingCost??0,"number")}${field("Fulfillment country","fulfillmentCountry",p?.fulfillmentCountry||"")}${field("Estimated shipping time","estimatedShippingTime",p?.estimatedShippingTime||"")}${field("Supplier notes","supplierNotes",p?.supplierNotes||"","textarea",true)}${field("Manual order","manualOrder",p?.manualOrder??STORE.products.length+1,"number")}${selectField("Status","status",p?.status||"Active",[["Active","Active"],["Draft","Draft"],["Archived","Archived"]])}<div class="wide check-row">${boolField("Featured","featured",p?.featured)}${boolField("Publish","published",p?.published)}</div><div class="wide admin-actions"><button class="admin-btn dark" type="submit">${p?"Save changes":"Add product"}</button>${p?`<button class="admin-btn" type="button" id="duplicateProduct">Duplicate</button><button class="admin-btn" type="button" id="cancelEdit">Cancel</button>`:""}</div></form></div><div class="admin-card"><h3>Catalogue <small style="color:#7c8794;font-weight:400">(${STORE.products.length} products — no fixed limit)</small></h3><div class="admin-field"><label>Search</label><input id="productSearch" placeholder="Search name, SKU, category"></div><div id="adminProductList" style="margin-top:10px"></div></div>`}
function ordersView(){return `<div class="admin-card"><h3>Orders</h3>${STORE.orders.length?STORE.orders.map(o=>`<div class="order-row"><div class="order-head"><strong>${escapeHtml(o.id)}</strong><span class="status">${escapeHtml(o.orderStatus)}</span></div><p style="font-size:12px;color:#74808e;margin:7px 0">${escapeHtml(o.customer.name)} · ${escapeHtml(o.customer.email)} · ${money(o.total,o.currency)}</p><div class="admin-actions"><select class="order-status" data-order="${o.id}">${["Pending","Paid","Processing","Fulfilled","Shipped","Delivered","Cancelled","Refunded"].map(s=>`<option ${o.orderStatus===s?"selected":""}>${s}</option>`).join("")}</select><input class="tracking-input" data-order="${o.id}" placeholder="Tracking number" value="${escapeHtml(o.trackingNumber||"")}"><button class="admin-btn" data-saveorder="${o.id}">Save</button></div></div>`).join(""):`<p class="preview-note">No orders yet. Orders created in this prototype are stored locally in this browser.</p>`}</div>`}
function brandingView(){return `<div class="admin-card"><h3>Branding</h3><form id="brandingForm" class="form-grid">${field("Brand name","name",STORE.brand.name)}${field("Tagline","tagline",STORE.brand.tagline)}${field("Logo image (data URL or hosted URL)","logoData",STORE.brand.logoData||"","text",true)}${field("Favicon (data URL or hosted URL)","faviconData",STORE.brand.faviconData||"","text",true)}<div class="wide"><p class="preview-note">For GitHub Pages, a hosted image URL or a small data URL can be used. The text logo remains the fallback.</p></div><div class="wide admin-actions"><button class="admin-btn dark">Save branding</button></div></form></div>`}
function designView(){const themes={minimal:["Minimal Premium","#0d1726","#7697bb","#f5f3ee"],midnight:["Midnight Luxe","#e9edf5","#8da6cf","#0b1020"],sage:["Soft Sage","#24352e","#729783","#edf2ed"],sand:["Warm Sand","#3b3027","#b18a64","#f4ede3"],rose:["Modern Rose","#3a2630","#b07c8f","#f5eef1"]};return `<div class="admin-card"><h3>Ready-made themes</h3><div class="theme-grid">${Object.entries(themes).map(([k,v])=>`<button class="theme-option ${STORE.theme.preset===k?"active":""}" data-theme="${k}"><div class="theme-swatch" style="background:linear-gradient(135deg,${v[1]},${v[2]})"></div><strong>${v[0]}</strong></button>`).join("")}</div></div><div class="admin-card"><h3>Manual design controls</h3><form id="designForm" class="form-grid">${field("Primary colour","primary",STORE.theme.primary,"color")}${field("Accent colour","accent",STORE.theme.accent,"color")}${field("Background colour","background",STORE.theme.background,"color")}${field("Text colour","text",STORE.theme.text,"color")}${field("Card colour","card",STORE.theme.card||"#ffffff","color")}${field("Card radius (px)","radius",STORE.theme.radius,"number")}${selectField("Button style","button",STORE.theme.button,[["pill","Pill"],["soft","Soft"],["square","Square"]])}${selectField("Font","font",STORE.theme.font,[["Inter","Inter / System"],["Georgia","Georgia"],["Trebuchet MS","Trebuchet MS"],["Arial","Arial"],["Courier New","Courier New"]])}<div class="wide admin-actions"><button class="admin-btn dark">Save Theme</button><button type="button" class="admin-btn" id="resetTheme">Reset Theme</button></div></form></div>`}
function homepageView(){return `<div class="admin-card"><h3>Announcement</h3><form id="homepageForm"><div class="form-grid">${field("Announcement bar","announcement",STORE.announcement,"text",true)}${field("Hero kicker","kicker",STORE.hero.kicker)}${field("Hero headline","title",STORE.hero.title,"text",true)}${field("Hero description","description",STORE.hero.description,"textarea",true)}${field("CTA text","cta",STORE.hero.cta)}${field("Featured section title","productsTitle",$("#productsTitle")?.textContent||"Featured Finds")}${field("Benefit 1 title","b1t",STORE.benefits[0].title)}${field("Benefit 1 text","b1x",STORE.benefits[0].text)}${field("Benefit 2 title","b2t",STORE.benefits[1].title)}${field("Benefit 2 text","b2x",STORE.benefits[1].text)}${field("Benefit 3 title","b3t",STORE.benefits[2].title)}${field("Benefit 3 text","b3x",STORE.benefits[2].text)}<div class="wide check-row">${boolField("Show only Featured products on homepage","featuredOnly",STORE.homepage.featuredOnly)}</div><div class="wide admin-actions"><button class="admin-btn dark">Save homepage</button></div></div></form></div><div class="admin-card"><h3>FAQ manager</h3><div id="faqAdminList">${STORE.faqs.map((f,i)=>`<div class="admin-card" style="margin:8px 0;background:#f8fafb"><div class="form-grid">${field("Question",`fq${i}`,f.q,"text",true)}${field("Answer",`fa${i}`,f.a,"textarea",true)}</div><button class="admin-btn danger" data-deletefaq="${i}">Delete FAQ</button></div>`).join("")}</div><button class="admin-btn" id="addFaq">+ Add FAQ</button><button class="admin-btn dark" id="saveFaq">Save FAQs</button></div>`}
function paymentView(){return `<div class="admin-card"><h3>Payment configuration</h3><form id="paymentForm" class="form-grid">${selectField("Gateway","gateway",STORE.payment.gateway,[["Razorpay","Razorpay"],["PayPal","PayPal"],["Stripe","Stripe"],["Custom","Custom gateway"]])}${selectField("Currency","currency",STORE.payment.currency,[["USD","USD"],["GBP","GBP"],["EUR","EUR"],["AUD","AUD"],["INR","INR"]])}${field("Public/key identifier","publicKey",STORE.payment.publicKey||"","text",true)}${field("Secure checkout URL / backend endpoint","checkoutEndpoint",STORE.payment.checkoutEndpoint||"","url",true)}<div class="wide check-row">${boolField("Online payment enabled","online",STORE.payment.online)}${boolField("COD enabled","cod",STORE.payment.cod)}</div><div class="wide">${field("Payment fee %","paymentFeePercent",STORE.profit.paymentFeePercent,"number")}${field("Fixed payment fee","paymentFixed",STORE.profit.paymentFixed,"number")}</div><p class="preview-note wide">Never place gateway secret keys, private API keys or database passwords here. The frontend should call only a secure backend/serverless checkout endpoint.</p><div class="wide admin-actions"><button class="admin-btn dark">Save payment</button></div></form></div>`}
function shippingView(){return `<div class="admin-card"><h3>Shipping</h3><form id="shippingForm" class="form-grid">${field("Shipping countries","countries",STORE.shipping.countries,"text",true)}${field("Shipping text","shippingText",STORE.shipping.shippingText,"textarea",true)}${field("Estimated delivery text","deliveryText",STORE.shipping.deliveryText,"textarea",true)}${field("Return policy","returnsText",STORE.shipping.returnsText,"textarea",true)}<div class="wide admin-actions"><button class="admin-btn dark">Save shipping</button></div></form></div>`}
function seoView(){return `<div class="admin-card"><h3>SEO & Pinterest sharing</h3><form id="seoForm" class="form-grid">${field("Page title","title",STORE.seo.title,"text",true)}${field("Meta description","description",STORE.seo.description,"textarea",true)}${field("Open Graph title","ogTitle",STORE.seo.ogTitle,"text",true)}${field("Open Graph description","ogDescription",STORE.seo.ogDescription,"textarea",true)}${field("Social sharing image URL","ogImage",STORE.seo.ogImage||"","url",true)}<div class="wide preview-note">Open Graph metadata is included in index.html. For a production site, generate/update these tags server-side or during deployment if you need per-product previews.</div><div class="wide admin-actions"><button class="admin-btn dark">Save SEO</button></div></form></div>`}
function socialView(){return `<div class="admin-card"><h3>Social links</h3><form id="socialForm" class="form-grid">${Object.entries(STORE.social).map(([k,v])=>field(k,k,v,"url")).join("")}<div class="wide admin-actions"><button class="admin-btn dark">Save social links</button></div></form></div>`}
function backupView(){return `<div class="admin-grid"><div class="admin-card"><h3>Export Store Data</h3><p class="preview-note">Downloads products, settings, FAQs and prototype orders as JSON. This is a backup, not a secure production database.</p><button class="admin-btn dark" id="exportData">Download JSON backup</button></div><div class="admin-card"><h3>Import Store Data</h3><input id="importFile" type="file" accept=".json,application/json"><p class="preview-note">Importing replaces the current prototype store data after validation.</p><button class="admin-btn dark" id="importData">Import selected file</button></div></div>`}
function settingsView(){return `<div class="admin-card"><h3>Prototype settings</h3><form id="settingsForm">${field("Admin PIN","pin",STORE.admin.pin,"password")}${field("Profit fee %","fee",STORE.profit.paymentFeePercent,"number")}${field("Fixed fee","fixed",STORE.profit.paymentFixed,"number")}<div class="admin-actions"><button class="admin-btn dark">Save settings</button><button class="admin-btn danger" type="button" id="resetStore">Reset all demo store data</button></div></form><p class="preview-note" style="margin-top:15px">This PIN is client-side for demonstration only. Anyone with access to the browser source/storage can inspect it. Replace with secure authentication before production.</p></div>`}
function bindAdminView(){
 $$("[data-goto]").forEach(b=>b.onclick=()=>{adminTab=b.dataset.goto;renderAdmin()});
 const pf=$("#productForm");if(pf){pf.onsubmit=e=>{e.preventDefault();const f=new FormData(pf);let id=f.get("id").trim();let images=[f.get("mainImage").trim(),...String(f.get("additionalImages")||"").split(/\n+/).map(x=>x.trim()).filter(Boolean)].filter(Boolean);let variants=[];try{variants=JSON.parse(f.get("variants")||"[]")}catch(err){alert("Variants JSON is invalid.");return}const obj={id,name:f.get("name").trim(),short:f.get("short").trim(),description:f.get("description").trim(),price:Number(f.get("price")),compare:Number(f.get("compare"))||0,currency:f.get("currency"),category:f.get("category").trim()||"General",tags:String(f.get("tags")).split(",").map(x=>x.trim()).filter(Boolean),variants,shipping:f.get("shipping").trim(),supplier:f.get("supplier").trim(),supplierUrl:f.get("supplierUrl").trim(),supplierProductId:f.get("supplierProductId").trim(),supplierCost:Number(f.get("supplierCost"))||0,shippingCost:Number(f.get("shippingCost"))||0,supplierNotes:f.get("supplierNotes").trim(),fulfillmentCountry:f.get("fulfillmentCountry").trim(),estimatedShippingTime:f.get("estimatedShippingTime").trim(),status:f.get("status"),featured:f.has("featured"),published:f.has("published"),createdAt:STORE.products.find(p=>p.id===editingProductId)?.createdAt||new Date().toISOString(),manualOrder:Number(f.get("manualOrder"))||STORE.products.length+1,images};if(editingProductId){const i=STORE.products.findIndex(p=>p.id===editingProductId);if(i>=0)STORE.products[i]=obj}else{if(STORE.products.some(p=>p.id===id)){alert("Product ID/SKU already exists.");return}STORE.products.push(obj)}editingProductId=null;saveAndRender("Product saved successfully")};$("#cancelEdit")?.addEventListener("click",()=>{editingProductId=null;renderAdmin()});$("#duplicateProduct")?.addEventListener("click",()=>{const p=STORE.products.find(x=>x.id===editingProductId);if(!p)return;const copy=JSON.parse(JSON.stringify(p));copy.id=p.id+"-COPY";copy.name=p.name+" Copy";copy.published=false;copy.createdAt=new Date().toISOString();STORE.products.push(copy);editingProductId=null;saveAndRender("Product duplicated")};$("#productSearch").oninput=()=>renderAdminProductList()}
 renderAdminProductList();
 $$("[data-edit]").forEach(b=>b.onclick=()=>{editingProductId=b.dataset.edit;renderAdmin()});$$("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("Delete this product?")){STORE.products=STORE.products.filter(p=>p.id!==b.dataset.delete);saveAndRender("Product deleted")}});$$("[data-publish]").forEach(b=>b.onclick=()=>{const p=STORE.products.find(p=>p.id===b.dataset.publish);if(p){p.published=!p.published;saveAndRender(p.published?"Product published":"Product unpublished")}});$$("[data-feature]").forEach(b=>b.onclick=()=>{const p=STORE.products.find(p=>p.id===b.dataset.feature);if(p){p.featured=!p.featured;saveAndRender(p.featured?"Product featured":"Product unfeatured")}});

 const bf=$("#brandingForm");if(bf)bf.onsubmit=e=>{e.preventDefault();const f=new FormData(bf);STORE.brand.name=f.get("name");STORE.brand.tagline=f.get("tagline");STORE.brand.logoData=f.get("logoData");STORE.brand.faviconData=f.get("faviconData");saveAndRender("Branding saved successfully")};
 const df=$("#designForm");if(df)df.onsubmit=e=>{e.preventDefault();const f=new FormData(df);Object.assign(STORE.theme,{primary:f.get("primary"),accent:f.get("accent"),background:f.get("background"),text:f.get("text"),card:f.get("card"),radius:Number(f.get("radius"))||18,button:f.get("button"),font:f.get("font")});STORE.theme.preset="custom";saveAndRender("Theme saved successfully")};
 $$("[data-theme]").forEach(b=>b.onclick=()=>applyPreset(b.dataset.theme));$("#resetTheme")?.addEventListener("click",()=>{STORE.theme=cloneDefaults().theme;saveAndRender("Theme reset")});
 const hf=$("#homepageForm");if(hf)hf.onsubmit=e=>{e.preventDefault();const f=new FormData(hf);STORE.announcement=f.get("announcement");STORE.hero={kicker:f.get("kicker"),title:f.get("title"),description:f.get("description"),cta:f.get("cta")};STORE.benefits=[{title:f.get("b1t"),text:f.get("b1x")},{title:f.get("b2t"),text:f.get("b2x")},{title:f.get("b3t"),text:f.get("b3x")}];STORE.homepage.featuredOnly=f.has("featuredOnly");saveAndRender("Homepage saved successfully")};
 $$("[data-deletefaq]").forEach(b=>b.onclick=()=>{STORE.faqs.splice(Number(b.dataset.deletefaq),1);saveAndRender("FAQ deleted")});$("#addFaq")?.addEventListener("click",()=>{STORE.faqs.push({q:"New question",a:"Answer"});renderAdmin()});$("#saveFaq")?.addEventListener("click",()=>{STORE.faqs=STORE.faqs.map((x,i)=>{const q=$(`[name="fq${i}"]`),a=$(`[name="fa${i}"]`);return{q:q?.value||x.q,a:a?.value||x.a}});saveAndRender("FAQs saved successfully")});
 const pay=$("#paymentForm");if(pay)pay.onsubmit=e=>{e.preventDefault();const f=new FormData(pay);STORE.payment.gateway=f.get("gateway");STORE.payment.currency=f.get("currency");STORE.payment.publicKey=f.get("publicKey");STORE.payment.checkoutEndpoint=f.get("checkoutEndpoint");STORE.payment.online=f.has("online");STORE.payment.cod=f.has("cod");STORE.profit.paymentFeePercent=Number(f.get("paymentFeePercent"))||0;STORE.profit.paymentFixed=Number(f.get("paymentFixed"))||0;saveAndRender("Payment settings saved")};
 const sf=$("#shippingForm");if(sf)sf.onsubmit=e=>{e.preventDefault();const f=new FormData(sf);STORE.shipping={countries:f.get("countries"),shippingText:f.get("shippingText"),deliveryText:f.get("deliveryText"),returnsText:f.get("returnsText")};saveAndRender("Shipping settings saved")};
 const seo=$("#seoForm");if(seo)seo.onsubmit=e=>{e.preventDefault();const f=new FormData(seo);STORE.seo={title:f.get("title"),description:f.get("description"),ogTitle:f.get("ogTitle"),ogDescription:f.get("ogDescription"),ogImage:f.get("ogImage")};saveAndRender("SEO settings saved")};
 const so=$("#socialForm");if(so)so.onsubmit=e=>{e.preventDefault();const f=new FormData(so);for(const k of Object.keys(STORE.social))STORE.social[k]=f.get(k)||"#";saveAndRender("Social links saved")};
 const ss=$("#settingsForm");if(ss)ss.onsubmit=e=>{e.preventDefault();const f=new FormData(ss);STORE.admin.pin=f.get("pin");STORE.profit.paymentFeePercent=Number(f.get("fee"))||0;STORE.profit.paymentFixed=Number(f.get("fixed"))||0;saveAndRender("Settings saved")};$("#resetStore")?.addEventListener("click",()=>{if(confirm("Reset all store data to the demo defaults?")){resetStore();STORE=getStore();editingProductId=null;saveStore(STORE);renderStore();renderAdmin();toast("Demo store reset")}});

 $$("[data-saveorder]").forEach(b=>b.onclick=()=>{const o=STORE.orders.find(o=>o.id===b.dataset.saveorder);if(!o)return;o.orderStatus=$(`.order-status[data-order="${o.id}"]`).value;o.trackingNumber=$(`.tracking-input[data-order="${o.id}"]`).value;saveAndRender("Order updated")});
 $("#exportData")?.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(STORE,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="velmora-store-backup.json";a.click();URL.revokeObjectURL(a.href)});
 $("#importData")?.addEventListener("click",async()=>{const file=$("#importFile").files[0];if(!file){alert("Choose a JSON backup first.");return}try{const data=JSON.parse(await file.text());if(!Array.isArray(data.products)||!data.brand||!data.theme)throw new Error("Invalid VELMORA backup");STORE=mergeDeep(cloneDefaults(),data);saveAndRender("Store data imported successfully")}catch(e){alert("Import failed: "+e.message)}})
}
function renderAdminProductList(){const el=$("#adminProductList");if(!el)return;const q=($("#productSearch")?.value||"").toLowerCase();const list=STORE.products.filter(p=>[p.name,p.id,p.category,...(p.tags||[])].join(" ").toLowerCase().includes(q));el.innerHTML=list.map(p=>`<div class="product-admin-row"><img src="${escapeHtml(productImage(p))}" alt=""><div><h4>${escapeHtml(p.name)}</h4><p>${escapeHtml(p.id)} · ${money(p.price,p.currency)} · ${p.published?"Published":"Unpublished"} · ${p.featured?"Featured":"Standard"}</p></div><div class="admin-actions"><button class="admin-btn" data-edit="${p.id}">Edit</button><button class="admin-btn" data-duplicate-row="${p.id}">Duplicate</button><button class="admin-btn" data-publish="${p.id}">${p.published?"Unpublish":"Publish"}</button><button class="admin-btn" data-feature="${p.id}">${p.featured?"Unfeature":"Feature"}</button><button class="admin-btn danger" data-delete="${p.id}">Delete</button></div></div>`).join("")}
function applyPreset(k){const presets={minimal:["#0d1726","#7697bb","#f5f3ee","#182131","#fff"],midnight:["#e9edf5","#8da6cf","#0b1020","#edf1f7","#141b29"],sage:["#24352e","#729783","#edf2ed","#26352e","#fff"],sand:["#3b3027","#b18a64","#f4ede3","#3b3027","#fff"],rose:["#3a2630","#b07c8f","#f5eef1","#3a2630","#fff"]};const p=presets[k];if(!p)return;STORE.theme={...STORE.theme,preset:k,primary:p[0],accent:p[1],background:p[2],text:p[3],card:p[4]};saveAndRender("Theme applied successfully")}
function bindProductList(){renderAdminProductList()}
