/* VELMORA storefront, cart and payment adapter */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let CART=JSON.parse(localStorage.getItem("velmora_cart")||"[]");
let activeCategory="All", detailProduct=null, detailImage=0;

function money(n,c=STORE.payment.currency||"USD"){try{return new Intl.NumberFormat(undefined,{style:"currency",currency:c}).format(Number(n)||0)}catch(e){return `${c} ${(Number(n)||0).toFixed(2)}`}}
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function imgFallback(name){return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="900"><rect width="100%" height="100%" fill="#eef0f1"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#7b8592" font-family="Arial" font-size="30">${name}</text></svg>`)}`
}
function productImage(p){return (p.images&&p.images[0])||imgFallback(p.name)}
function applyTheme(){const t=STORE.theme;document.documentElement.style.setProperty("--primary",t.primary);document.documentElement.style.setProperty("--accent",t.accent);document.documentElement.style.setProperty("--bg",t.background);document.documentElement.style.setProperty("--text",t.text);document.documentElement.style.setProperty("--card",t.card||"#fff");document.documentElement.style.setProperty("--radius",`${t.radius}px`);document.documentElement.style.setProperty("--button-radius",t.button==="square"?"10px":t.button==="soft"?"12px":"999px");document.documentElement.style.setProperty("--font",fontStack(t.font));}
function fontStack(f){return ({Inter:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif',Georgia:'Georgia,serif',"Trebuchet MS":'"Trebuchet MS",sans-serif',"Arial":'Arial,sans-serif',"Courier New":'"Courier New",monospace'})[f]||'Inter,ui-sans-serif,system-ui,sans-serif'}
function renderStore(){
 applyTheme();
 document.title=STORE.seo.title||`${STORE.brand.name} — ${STORE.brand.tagline}`;
 $("#announcement").textContent=STORE.announcement;
 $("#brandLink").textContent=STORE.brand.name; $("#footerBrand").textContent=STORE.brand.name;
 $("#heroKicker").textContent=STORE.hero.kicker; $("#heroTitle").textContent=STORE.hero.title; $("#heroDescription").textContent=STORE.hero.description; $("#heroCta").textContent=STORE.hero.cta;
 $("#footerDescription").textContent=STORE.footer.description;
 $("#shippingLink").href=STORE.footer.shipping||"#";$("#returnsLink").href=STORE.footer.returns||"#";$("#privacyLink").href=STORE.footer.privacy||"#";$("#termsLink").href=STORE.footer.terms||"#";$("#contactLink").href=STORE.footer.contact||"#";
 $("#year").textContent=new Date().getFullYear();
 const socials=Object.entries(STORE.social).filter(([,v])=>v&&v!=="#");$("#socialLinks").innerHTML=socials.map(([k,v])=>`<a href="${escapeHtml(v)}" target="_blank" rel="noopener">${escapeHtml(k)}</a>`).join("")||"<span class='footer-label'>Links can be added in Admin</span>";
 $("#benefit1").innerHTML=`<strong>${escapeHtml(STORE.benefits[0]?.title||"Curated selection")}</strong><p>${escapeHtml(STORE.benefits[0]?.text||"")}</p>`;
 $("#benefit2").innerHTML=`<strong>${escapeHtml(STORE.benefits[1]?.title||"Secure checkout")}</strong><p>${escapeHtml(STORE.benefits[1]?.text||"")}</p>`;
 $("#benefit3").innerHTML=`<strong>${escapeHtml(STORE.benefits[2]?.title||"Worldwide delivery")}</strong><p>${escapeHtml(STORE.benefits[2]?.text||"")}</p>`;
 renderNav();renderCategories();renderProducts();renderCart();
}
function renderNav(){const links=[["Collection","#products"],["FAQ","#faqSection"],["Shipping",STORE.footer.shipping||"#"]];$("#desktopNav").innerHTML=links.map(x=>`<a href="${x[1]}">${x[0]}</a>`).join("");$("#mobileNavLinks").innerHTML=links.map(x=>`<a href="${x[1]}" data-close="mobileNavModal">${x[0]}</a>`).join("")+`<button class="btn btn-primary full" id="mobileNavCart">Open bag</button>`;$("#mobileNavCart")?.addEventListener("click",()=>{closeModal("mobileNavModal");openCart()})}
function renderCategories(){const cats=["All",...new Set(STORE.products.filter(p=>p.published).map(p=>p.category).filter(Boolean))];$("#categoryRow").innerHTML=cats.map(c=>`<button class="category-chip ${activeCategory===c?"active":""}" data-cat="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join("");$$("[data-cat]").forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderCategories();renderProducts()})}
function getVisibleProducts(){let list=STORE.products.filter(p=>p.published&&(!STORE.homepage.featuredOnly||p.featured)&& (activeCategory==="All"||p.category===activeCategory));const sort=$("#sortProducts")?.value||"newest";if(sort==="low")list.sort((a,b)=>a.price-b.price);else if(sort==="high")list.sort((a,b)=>b.price-a.price);else if(sort==="manual")list.sort((a,b)=>(a.manualOrder||0)-(b.manualOrder||0));else list.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return list}
function renderProducts(){const list=getVisibleProducts();$("#productGrid").innerHTML=list.map(p=>{const disc=p.compare>p.price?Math.round((1-p.price/p.compare)*100):0;return `<article class="product-card"><div class="product-image"><img loading="lazy" src="${escapeHtml(productImage(p))}" onerror="this.src='${imgFallback(p.name)}'" alt="${escapeHtml(p.name)}">${disc?`<span class="product-badge">-${disc}%</span>`:""}</div><div class="product-info"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.short)}</p><div class="price"><strong>${money(p.price,p.currency)}</strong>${p.compare?`<del>${money(p.compare,p.currency)}</del>`:""}</div><div class="product-actions"><button class="small-btn" data-view="${escapeHtml(p.id)}">View</button><button class="small-btn primary" data-add="${escapeHtml(p.id)}">Add to Cart</button></div></div></article>`}).join("");$("#emptyProducts").classList.toggle("hidden",!list.length);$$("[data-view]").forEach(b=>b.onclick=()=>openProduct(b.dataset.view));$$("[data-add]").forEach(b=>b.onclick=()=>addToCart(b.dataset.add))}
function addToCart(id,qty=1){const p=STORE.products.find(x=>x.id===id);if(!p)return;const row=CART.find(x=>x.id===id);if(row)row.qty+=qty;else CART.push({id,qty});persistCart();renderCart();openCart()}
function persistCart(){localStorage.setItem("velmora_cart",JSON.stringify(CART))}
function cartRows(){return CART.map(x=>{const p=STORE.products.find(p=>p.id===x.id);return p?{...x,p}:null}).filter(Boolean)}
function renderCart(){const rows=cartRows();$("#cartCount").textContent=rows.reduce((s,x)=>s+x.qty,0);$("#cartItems").innerHTML=rows.length?rows.map(x=>`<div class="cart-line"><img src="${escapeHtml(productImage(x.p))}" alt=""><div><h4>${escapeHtml(x.p.name)}</h4><small>${money(x.p.price,x.p.currency)}</small><div class="qty"><button data-dec="${x.id}">−</button><b>${x.qty}</b><button data-inc="${x.id}">+</button></div></div><button class="remove" data-remove="${x.id}">Remove</button></div>`).join(""):`<div class="empty-state"><p>Your bag is empty.</p><button class="btn btn-secondary" id="emptyContinue">Explore finds</button></div>`;$("#cartTotal").textContent=money(rows.reduce((s,x)=>s+x.p.price*x.qty,0));$$("[data-inc]").forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));$$("[data-dec]").forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));$$("[data-remove]").forEach(b=>b.onclick=()=>removeCart(b.dataset.remove));$("#emptyContinue")?.addEventListener("click",()=>{closeCart();$("#products").scrollIntoView()})}
function changeQty(id,d){const x=CART.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)CART=CART.filter(y=>y.id!==id);persistCart();renderCart()}
function removeCart(id){CART=CART.filter(x=>x.id!==id);persistCart();renderCart()}
function openCart(){$("#cartDrawer").classList.add("open");$("#drawerBackdrop").classList.add("open");document.body.classList.add("no-scroll")}
function closeCart(){$("#cartDrawer").classList.remove("open");$("#drawerBackdrop").classList.remove("open");document.body.classList.remove("no-scroll")}
function openProduct(id){const p=STORE.products.find(x=>x.id===id);if(!p)return;detailProduct=p;detailImage=0;renderProductDetail();$("#productModal").classList.add("open");document.body.classList.add("no-scroll")}
function renderProductDetail(){const p=detailProduct;const images=(p.images&&p.images.length?p.images:[productImage(p)]);const variants=(p.variants||[]).map((v,i)=>`<div class="variant-group"><label>${escapeHtml(v.name)}</label><div class="variant-options">${(v.options||[]).map((o,j)=>`<button class="variant-option ${j===0?"active":""}" data-variant="${i}">${escapeHtml(o)}</button>`).join("")}</div></div>`).join("");$("#productDetailContent").innerHTML=`<div class="detail-grid"><div><img class="detail-main-img" src="${escapeHtml(images[detailImage]||productImage(p))}" alt="${escapeHtml(p.name)}"><div class="gallery">${images.map((im,i)=>`<img class="${i===detailImage?"active":""}" src="${escapeHtml(im)}" data-gallery="${i}" alt="">`).join("")}</div></div><div class="detail-info"><span class="eyebrow">${escapeHtml(p.category||"VELMORA")}</span><h2>${escapeHtml(p.name)}</h2><div class="price"><strong>${money(p.price,p.currency)}</strong>${p.compare?`<del>${money(p.compare,p.currency)}</del>`:""}</div><p class="description">${escapeHtml(p.description||p.short||"")}</p>${p.features?.length?`<ul>${p.features.map(f=>`<li>${escapeHtml(f)}</li>`).join("")}</ul>`:""}${variants}<div class="detail-meta">${escapeHtml(p.shipping||"Shipping details available at checkout.")}</div><div class="detail-buy"><input id="detailQty" type="number" min="1" value="1"><button class="btn btn-secondary" id="detailAdd">Add to Cart</button><button class="btn btn-primary" id="detailBuy">Buy Now</button></div></div></div>`;$$("[data-gallery]").forEach(b=>b.onclick=()=>{detailImage=Number(b.dataset.gallery);renderProductDetail()});$("#detailAdd").onclick=()=>{addToCart(p.id,Math.max(1,Number($("#detailQty").value)||1));closeModal("productModal")};$("#detailBuy").onclick=()=>{addToCart(p.id,Math.max(1,Number($("#detailQty").value)||1));closeModal("productModal");openCart();setTimeout(openCheckout,150)}}
function openCheckout(){const rows=cartRows();if(!rows.length)return;const total=rows.reduce((s,x)=>s+x.p.price*x.qty,0);$("#checkoutContent").innerHTML=`<span class="eyebrow">SECURE CHECKOUT</span><h2>Complete your order</h2><div class="checkout-summary">${rows.map(x=>`<div><span>${escapeHtml(x.p.name)} × ${x.qty}</span><strong>${money(x.p.price*x.qty,x.p.currency)}</strong></div>`).join("")}<div><strong>Subtotal</strong><strong>${money(total)}</strong></div></div><form id="checkoutForm" class="checkout-form"><div class="field"><label>Full name</label><input name="name" required></div><div class="field"><label>Phone</label><input name="phone" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Country</label><input name="country" required></div><div class="field wide"><label>Address</label><textarea name="address" required></textarea></div><div class="field"><label>City</label><input name="city" required></div><div class="field"><label>State / Province</label><input name="state"></div><div class="field"><label>Postal code</label><input name="postal" required></div>${STORE.payment.cod?`<div class="field wide"><label>Payment method</label><select name="paymentMethod"><option value="online">Online payment</option><option value="cod">Cash on Delivery</option></select></div>`:`<input type="hidden" name="paymentMethod" value="online">`}<div class="checkout-note wide">Cash on Delivery availability depends on destination and fulfillment partner. Online payments require a secure backend checkout endpoint; this static prototype never exposes secret keys.</div><button class="btn btn-primary wide" type="submit">Continue to payment</button></form>`;$("#checkoutModal").classList.add("open");document.body.classList.add("no-scroll");$("#checkoutForm").onsubmit=handleCheckout}
async function handleCheckout(e){e.preventDefault();const fd=new FormData(e.target);const rows=cartRows();const total=rows.reduce((s,x)=>s+x.p.price*x.qty,0);const order={id:"VM-"+Date.now().toString(36).toUpperCase(),customer:{name:fd.get("name"),phone:fd.get("phone"),email:fd.get("email"),country:fd.get("country"),address:fd.get("address"),city:fd.get("city"),state:fd.get("state"),postal:fd.get("postal")},products:rows.map(x=>({id:x.p.id,name:x.p.name,quantity:x.qty,price:x.p.price,supplier:x.p.supplier})),total,currency:STORE.payment.currency,paymentStatus:"Pending",orderStatus:"Pending",shippingStatus:"Pending",trackingNumber:"",dateTime:new Date().toISOString()};STORE.orders.unshift(order);saveStore(STORE);
 if(fd.get("paymentMethod")==="cod"){alert("COD order saved in this prototype. Actual COD fulfillment must be connected to a supported partner.");CART=[];persistCart();closeModal("checkoutModal");closeCart();renderCart();return}
 if(STORE.payment.checkoutEndpoint){try{const r=await fetch(STORE.payment.checkoutEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(order)});if(!r.ok)throw new Error("Checkout endpoint returned an error");const data=await r.json().catch(()=>({}));if(data.url)location.href=data.url;else alert("Order sent to the secure checkout endpoint.");CART=[];persistCart();closeModal("checkoutModal");closeCart();renderCart()}catch(err){alert("Secure checkout endpoint could not be reached. No payment secret was exposed in the browser.")}}else{alert("Prototype order saved. Add a secure serverless checkout endpoint in Admin → Payment to enable real online payment.");}}
function closeModal(id){$("#"+id)?.classList.remove("open");if(!document.querySelector(".modal.open")&&!$("#cartDrawer").classList.contains("open"))document.body.classList.remove("no-scroll")}
$("#openCart").onclick=openCart;$("#drawerBackdrop").onclick=closeCart;$("#continueShopping").onclick=closeCart;$("#checkoutBtn").onclick=openCheckout;$("#sortProducts").onchange=renderProducts;$("#openNav").onclick=()=>{$("#mobileNavModal").classList.add("open");document.body.classList.add("no-scroll")};
$$("[data-close]").forEach(b=>b.onclick=()=>{const id=b.dataset.close;if(id==="cartDrawer")closeCart();else closeModal(id)});
document.addEventListener("click",e=>{if(e.target.matches(".faq-q"))e.target.parentElement.classList.toggle("open");if(e.target.matches("[data-close='mobileNavModal']"))closeModal("mobileNavModal")});
renderStore();
