/* VELMORA public defaults. Production data is served by the secure backend. */
const VELMORA_DEFAULTS = {
  brand:{name:"VELMORA",tagline:"Better things for everyday life.",logoData:"",faviconData:""},
  announcement:"Free shipping on selected orders • Secure checkout",
  hero:{kicker:"THOUGHTFULLY SELECTED",title:"Better things for everyday life.",description:"Discover useful, beautiful finds chosen to bring a little more ease to the everyday.",cta:"Explore the collection"},
  benefits:[
    {title:"Curated selection",text:"Thoughtfully selected products with a focus on everyday usefulness."},
    {title:"Secure checkout",text:"A clean checkout experience designed for simple, confident shopping."},
    {title:"Worldwide delivery",text:"Shipping options can be configured by destination and fulfillment partner."}
  ],
  footer:{description:"VELMORA curates modern everyday products for people who value thoughtful design and practical details.",shipping:"#",returns:"#",privacy:"#",terms:"#",contact:"mailto:hello@example.com"},
  social:{Pinterest:"#",Instagram:"#",Facebook:"#",TikTok:"#",YouTube:"#",Other:"#"},
  seo:{title:"VELMORA — Better things for everyday life.",description:"Thoughtfully selected everyday finds for modern life.",ogTitle:"VELMORA — Better things for everyday life.",ogDescription:"Thoughtfully selected everyday finds for modern life.",ogImage:""},
  shipping:{countries:"UK, Europe, USA, Australia",shippingText:"Shipping availability depends on destination and fulfillment partner.",deliveryText:"Estimated delivery times vary by destination and supplier.",returnsText:"Returns are subject to the store return policy."},
  payment:{gateway:"Razorpay",currency:"USD",publicKey:"",checkoutEndpoint:"/api/checkout-create",online:true,cod:false},
  profit:{paymentFeePercent:2.9,paymentFixed:0.30},
  theme:{preset:"minimal",primary:"#0d1726",accent:"#7697bb",background:"#f5f3ee",text:"#182131",card:"#ffffff",radius:18,button:"pill",font:"Inter"},
  homepage:{featuredOnly:true},
  products:[
    {id:"VM-001",name:"Aero Desk Organizer",short:"A calm home for pens, notes and small essentials.",description:"A clean, modular desk organizer designed for modern workspaces and everyday routines.",features:["Modular compartments","Compact footprint","Easy-clean finish"],price:39.00,compare:49.00,currency:"USD",category:"Home",tags:["desk","organization","workspace"],variants:[{name:"Colour",options:["Stone","Charcoal"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:true,published:true,createdAt:"2026-09-18T10:00:00Z",manualOrder:1,images:["https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-002",name:"Luma Ceramic Mug",short:"A quiet, tactile addition to slow mornings.",description:"A simple ceramic mug with a balanced shape and understated finish.",features:["Ceramic","Everyday size","Gift-ready aesthetic"],price:24.00,compare:29.00,currency:"USD",category:"Home",tags:["mug","ceramic","coffee"],variants:[{name:"Colour",options:["Sand","Cloud"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:true,published:true,createdAt:"2026-09-17T10:00:00Z",manualOrder:2,images:["https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-003",name:"Noma Travel Pouch",short:"A neat place for cables, chargers and small essentials.",description:"A compact organizer for daily carry and travel, with flexible internal storage.",features:["Lightweight","Multiple compartments","Travel-friendly"],price:31.00,compare:39.00,currency:"USD",category:"Travel",tags:["travel","organizer","carry"],variants:[{name:"Colour",options:["Olive","Black"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:true,published:true,createdAt:"2026-09-16T10:00:00Z",manualOrder:3,images:["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-004",name:"Sora Reading Light",short:"Soft, focused light for late pages and quiet corners.",description:"A minimal reading light concept with a warm, focused glow.",features:["Adjustable","Compact","Warm-light concept"],price:42.00,compare:55.00,currency:"USD",category:"Lifestyle",tags:["light","reading","home"],variants:[{name:"Finish",options:["Silver","Black"]}],shipping:"Ships in 5–10 business days.",status:"Active",featured:true,published:true,createdAt:"2026-09-15T10:00:00Z",manualOrder:4,images:["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-005",name:"Forma Bottle",short:"A refined everyday bottle with a clean silhouette.",description:"A reusable bottle concept made for desk, commute and weekend routines.",features:["Reusable","Leak-conscious lid","Easy-carry form"],price:28.00,compare:35.00,currency:"USD",category:"Lifestyle",tags:["bottle","daily","carry"],variants:[{name:"Colour",options:["Blue","Stone","Black"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:true,published:true,createdAt:"2026-09-14T10:00:00Z",manualOrder:5,images:["https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-006",name:"Arco Catchall Tray",short:"A simple landing place for keys and daily carry.",description:"A small catchall tray for keeping everyday objects organized.",features:["Compact","Minimal form","Easy to clean"],price:22.00,compare:27.00,currency:"USD",category:"Home",tags:["tray","organization","entryway"],variants:[{name:"Colour",options:["Sand","Charcoal"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:true,published:true,createdAt:"2026-09-13T10:00:00Z",manualOrder:6,images:["https://images.unsplash.com/photo-1616628182500-7f1c1b7e4e3f?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-007",name:"Milo Tech Stand",short:"A tidy stand for your phone and small devices.",description:"A clean desktop stand concept for keeping screens visible and surfaces clear.",features:["Stable base","Compact","Desk-friendly"],price:34.00,compare:42.00,currency:"USD",category:"Tech",tags:["phone","stand","desk"],variants:[{name:"Finish",options:["Silver","Graphite"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:true,published:true,createdAt:"2026-09-12T10:00:00Z",manualOrder:7,images:["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-008",name:"Eira Notebook",short:"A clean page for ideas, lists and plans.",description:"A minimal notebook concept for everyday notes and thoughtful planning.",features:["Lay-flat concept","Smooth pages","Minimal cover"],price:18.00,compare:22.00,currency:"USD",category:"Stationery",tags:["notebook","writing","planning"],variants:[{name:"Cover",options:["Ivory","Navy"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:false,published:true,createdAt:"2026-09-11T10:00:00Z",manualOrder:8,images:["https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-009",name:"Aster Cable Wraps",short:"Small details that keep charging cables under control.",description:"A simple set of cable wraps for tidier bags, desks and drawers.",features:["Reusable","Compact","Multi-pack concept"],price:14.00,compare:18.00,currency:"USD",category:"Tech",tags:["cable","desk","travel"],variants:[{name:"Set",options:["Neutral","Mixed"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:false,published:true,createdAt:"2026-09-10T10:00:00Z",manualOrder:9,images:["https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=80"]},
    {id:"VM-010",name:"Kova Key Hook",short:"A discreet home for the keys you reach for every day.",description:"A small wall-mounted hook concept for entryways and workspaces.",features:["Minimal footprint","Easy placement","Everyday utility"],price:19.00,compare:24.00,currency:"USD",category:"Home",tags:["keys","home","organization"],variants:[{name:"Finish",options:["Brass","Black"]}],shipping:"Ships in 3–7 business days.",status:"Active",featured:false,published:true,createdAt:"2026-09-09T10:00:00Z",manualOrder:10,images:["https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=900&q=80"]}
  ],
  faqs:[
    {q:"Where do you ship?",a:"Shipping availability and delivery estimates depend on destination and the fulfillment partner. See the shipping information shown at checkout."},
    {q:"Can I return an item?",a:"Returns are subject to the store's configured return policy and the product's eligibility. Contact the store before sending anything back."},
    {q:"Is Cash on Delivery available?",a:"Only where the connected fulfillment partner supports it. Availability depends on destination and fulfillment partner."},
    {q:"How does checkout work?",a:"The prototype collects order details and can hand off to a configured secure checkout endpoint. Real payment processing requires a backend."}
  ],
  orders:[]
};
function cloneDefaults(){return JSON.parse(JSON.stringify(VELMORA_DEFAULTS))}
function getStore(){return cloneDefaults()}
function saveStore(store){STORE=store;return store}
function mergeDeep(base,extra){if(!extra||typeof extra!=="object")return base; for(const k of Object.keys(extra)){if(extra[k]&&typeof extra[k]==="object"&&!Array.isArray(extra[k])&&base[k]&&typeof base[k]==="object")base[k]=mergeDeep(base[k],extra[k]);else base[k]=extra[k]} return base}
let STORE=getStore();
function resetStore(){STORE=cloneDefaults();saveStore(STORE)}
